### ISSUE TITLE
Can I use this on Ubuntu 15.04 64bit Desktop?

### ISSUE THREAD

**Issue by draft1** [jbradach/quick-lemp#1]
As I just want to have local development.

**Comment by jbradach** [comment]
Yes and no. I just tried both scripts on an Ubuntu 15.04 x64 VPS and had mixed results. The setup script worked, but you may not even want to bother with it for a local machine. It installs a new user and grants it sudo access, configures basic firewall settings (UFW), and adjusts sshd.

The stack script ran successfully except for configuring and starting uWSGI. In 15.04, [the default init system was changed to systemd](http://linux.slashdot.org/story/15/03/06/1448247/ubuntu-to-officially-switch-to-systemd-next-monday) and quick-lemp currently assumes Upstart.

If you're just using Nginx and PHP-FPM and don't need uWSGI, the 14.04 script should work just fine.

I'll aim to get a 15.04 version out in the near future.

**Comment by jbradach** [comment]
I've added a new version of each script intended to be compatible with 12.04, 13.04, 14.04, and 15.04. This one checks to see whether Upstart or systemd is in use and installs uWSGI appropriately.

quicklemp-ubuntu-setup.sh
quicklemp-ubuntu-stack.sh

I've tested this on 15.04 x64 several times so I believe it should work for you.
