### ISSUE TITLE
Your script is dangerous

### ISSUE THREAD

**Issue by ghost** [jbradach/quick-lemp#10]
I got locked out of a production box because you changed my SSH settings WTF put a warning or a way to revert it so it doesnt time out with a remote box lime mine did.

**Comment by jbradach** [comment]
Hello, Josh.

I'm sorry you had issues with my scripts. I made a point to include notices in a couple locations to help avoid this sort of scenario. For instance, when the setup script is done running, a notice is displayed advising the user to test their  settings prior to disconnecting.

The setup script doesn't require you to change your SSH port. In fact, just hitting enter at the New SSH Port prompt will keep the default.

[README.md](https://github.com/jbradach/quick-lemp/blob/master/README.md)

> You should read these scripts before running them so you know what they're doing. Changes may be necessary to meet your needs. 

[quicklemp-ubunutu-setup.sh](https://github.com/jbradach/quick-lemp/blob/master/quicklemp-ubuntu-setup.sh#L116)

> Open a new session to confirm your settings before logging out.
