### ISSUE TITLE
Optional uWSGI

### ISSUE THREAD

**Issue by lhwparis** [jbradach/quick-lemp#4]
first of all, thanks for the cool scripts.
have you thought about adding an FTP server?

**Comment by jbradach** [comment]
I haven't really though about it as I use SFTP for everything. I think the addition of an FTP server is outside of this project's scope for now.

**Comment by lhwparis** [comment]
ok thanks for the rapid answer :) what do you think about making things optional? for me i just need nginx + php not the python part so i would be happy if you can make these things optional inside the script so you can choose what you need.

**Comment by jbradach** [comment]
Skipping uWSGI installation is definitely something that could be added fairly easily. I've been thinking about adding functionality to override the defaults like this so I'm glad to know it would be useful!

I'll aim to add this the next time I do an update.

**Comment by jbradach** [comment]
uWSGI installation is no longer automatic.
