### ISSUE TITLE
PPA Update Required maybe?

### ISSUE THREAD

**Issue by danijeljw** [jbradach/quick-lemp#9]
### This PPA has been deprecated!

Please note that this PPA has been deprecated and you need to use ppa:ondrej/php that contains co-installable versions of PHP 5.5, PHP 5.6 and PHP 7.0.

PHP 5.6.23 has been the last upload into this repository.

To add the new PPA, do:     

sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php                                                                                                     - sudo apt-get update                                                                                                                                      

And the install correct PHP version:
- sudo apt-get install php7.0 # for PHP 7.0
- sudo apt-get install php5.6 # for PHP 5.6
- sudo apt-get install php5.5 # for PHP 5.5

The packages for extensions contain modules for all supported PHP versions and can be installed with (f.e. xdebug and APCu):
- sudo apt-get install php-xdebug php-apcu

For more thorought documentation on the migrations, please see: https://github.com/oerdnj/deb.sury.org/wiki/PPA-migration-to-ppa:ondrej-php

**Comment by jbradach** [comment]
Updated PPA and changed default PHP packages to 5.6. 1a4e7310619bec1a10e0aacadb2c250d394c9d49

Related  to #6.
